use anchor_lang::prelude::*;
use crate::{GameStatus, RoundResult};

#[account]
#[derive(InitSpace)]
pub struct GameState {
    pub player1: Pubkey,
    pub player2: Option<Pubkey>,
    // These two are useful at the beginning of each round
    pub p1_ready: bool,
    pub p2_ready: bool,
    // Increases by one every time a player wins
    pub p1_score: u16,
    pub p2_score: u16,
    pub board: [u8; 9],     // 0=empty, 1=X, 2=O
    pub move_count: u8,
    pub turn: u8,           // 1 or 2
    pub round: u16,
    pub status: GameStatus,
    pub last_round_result: Option<RoundResult>,
    pub wager_per_round: u64,
    // Randomly generated by the client
    pub game_id: u64,
    /// Used for letting one of the players end the round and claim the money if the other
    /// player takes too long:
    pub last_move_slot: u64,
    /// The game's state information will be stored in a PDA. We store the bump so the
    /// program doesn't need to recalculate it every time.
    pub bump: u8,
}

impl GameState {
    pub fn start_round(&mut self) -> Result<()> {
        self.status = GameStatus::RoundActive;
        self.round += 1;
        self.board = [0; 9];
        self.move_count = 0;
        self.turn = (self.round % 2) as u8 + 1;
        Ok(())
    }

    pub fn end_round(&mut self, result: RoundResult) -> Result<()> {
        self.status = GameStatus::BetweenRounds;
        self.last_round_result = Some(result.clone());
        self.p1_ready = false;
        self.p2_ready = false;
        match result {
            RoundResult::Player1Won => self.p1_score += 1,
            RoundResult::Player2Won => self.p2_score += 1,
            RoundResult::Draw => {}
        }
        Ok(())
    }

    pub fn apply_move(&mut self, cell: u8, color: u8) {
        self.board[cell as usize] = color;
    }

    /// Checks whether the last move resulted in a row or draw. Passing over the board
    /// coordinates and the player helps massively reduce the search space.
    pub fn check_board(&self, cell: u8, player: u8) -> Option<RoundResult> {
        let row = (cell / 3) as usize;
        let col = (cell % 3) as usize;

        fn player_won(player: u8) -> Option<RoundResult> {
            match player {
                1 => Some(RoundResult::Player1Won),
                2 => Some(RoundResult::Player2Won),
                _ => unreachable!(),
            }
        }

        // check col
        for i in 0..3 {
            if self.board[3*i + col] != player {
                break;
            }
            if i == 2 {
                return player_won(player);
            }
        }

        // check row
        for j in 0..3 {
            if self.board[3*row + j] != player {
                break;
            }
            if j == 2 {
                return player_won(player);
            }
        }

        // check diagonal
        if row == col {
            // we're on a diagonal
            for d in 0..3 {
                if self.board[3*d + d] != player {
                    break;
                }
                if d == 2 {
                    return player_won(player);
                }
            }
        }

        // check anti-diagonal
        if row + col == 2 {
            // we're on an anti-diagonal
            for d in 0..3 {
                if self.board[3*d + (2-d)] != player {
                    break;
                }
                if d == 2 {
                    return player_won(player);
                }
            }
        }

        // check for draw
        if self.move_count == 8 {
            return Some(RoundResult::Draw);
        }

        None
    }
}
